name: Test

on:
  push:
    tags:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  test:
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Maven verify
      run: mvn --batch-mode --update-snapshot verify

